name: gluon_vision_docs
dependencies:
- python
- sphinx>=1.5.5
- scipy
- numpy
- matplotlib
- sphinx_rtd_theme
- pip:
  - sphinx-gallery
  - mxnet-cu90==1.3.0b20180718
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
  - tqdm
  - requests
  - Pillow
  - opencv-python
